### PR TITLE
refactor(useClipboard): setString should wrapped with useCallback

### PR DESCRIPTION
**Pull request by liaoyinglong**
make setString immutable

### CODE REVIEW

**Comment by pvinis** [comment]
Could you update this PR if it is still relevant? Thanks!

**Comment by liaoyinglong** [comment]
@pvinis hi, now is updated

**Comment by pvinis** [comment]
I'll take a look soon, thank you!

**Comment by pvinis** [comment]
Note to self (and liao): Let's see if we could actually make a test for this. 🤔

**Comment by LinusU** [comment]
This is indirectly fixed by #76 since it replaces the `setString` with a static function.

It's probably better to just merge that one since they will cause merge-conflicts otherwise ☺️

**Comment by pvinis** [comment]
I guess we can close this now that #76 is merged. If it shouldn't please let me know. Thank you for the PR! 🙌

**Pull request closed without merging**
