### PR TITLE
[RN 0.65.x] Adapt unsubscription for new EventEmitter API

### PR DESCRIPTION
**Pull request by retyui**
# Summary

Issue: https://github.com/react-native-community/hooks/issues/243

```jsx
// React Native 0.65.x +
typeof Dimensions.removeListener //function
Dimensions.removeListener(...) // print warning
```

### What's required for testing (prerequisites)?

- React Native >= `0.65`

### What are the steps to reproduce (after prerequisites)?

```bash
npx react-native init rn66
cd rn66
yarn add @react-native-community/hooks
# update App.js (see code below)
yarn start
yarn android # start project on android
# tap on "Toggle" button
```

```tsx
// App.js

import React, {useState} from 'react';
import {Text, View, ScrollView, Button} from 'react-native';
import {
  useAccessibilityInfo,
  useAppState,
  useBackHandler,
  useCameraRoll,
  useClipboard,
  useDimensions,
  useImageDimensions,
  useKeyboard,
  useInteractionManager,
  useDeviceOrientation,
  useLayout,
} from '@react-native-community/hooks';

const img = {
  uri: 'https://occ-0-1068-92.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABeV0Af4XqVIi8qSUEeV_llbkH9B-TyiTGukOX7pSFxAuAyoc9q-e--ErSFvK4dLjE7tYDAr1L0PXAja28cDsLWwGdA_A.jpg?r=43c',
};

function Hooks() {
  const a = {
    AccessibilityInfo: useAccessibilityInfo(),
    AppState: useAppState(),
    BackHandler: useBackHandler(() => {
      return true;
    }),
    CameraRoll: useCameraRoll(),
    Clipboard: useClipboard(),
    Dimensions: useDimensions(),
    ImageDimensions: useImageDimensions(img),
    Keyboard: useKeyboard(),
    InteractionManager: useInteractionManager(),
    DeviceOrientation: useDeviceOrientation(),
    Layout: useLayout(),
  };

  return <Text>{JSON.stringify(a, null, 2)}</Text>;
}

function App() {
  const [s, setS] = useState(true);

  return (
    <View padding={50} flex={1}>
      <Button title="Toggle" onPress={() => setS(p => !p)} />
      <ScrollView
        style={{
          borderWidth: 1,
          borderColor: 'red',
          flex: 1,
        }}>
        {s ? <Hooks /> : null}
      </ScrollView>
    </View>
  );
}

export default App;
```

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |
| Web     |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I've created a snack to demonstrate the changes: LINK HERE

### CODE REVIEW

**Comment by pvinis** [comment]
:rocket: PR was released in [`v2.8.0`](https://github.com/react-native-community/hooks/releases/tag/v2.8.0) :rocket:

**Comment by KrisLau** [comment]
Still getting the error for `useKeyboard`
```
EventEmitter.removeListener('keyboardWillShow', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`. 
```

**Comment by retyui** [comment]
`useKeyboard` was modified in another PR:  https://github.com/react-native-community/hooks/pull/244

**Comment by retyui** [comment]
As I  understand RN team first, remove `EventEmitter.removeListener` but after time restore that method but added a warning

https://github.com/facebook/react-native/commit/035718ba97bb44c68f2a4ccdd95e537e3d28690c

**Pull request merged**
