### PR TITLE
fixes for useKeyboard

### PR DESCRIPTION
**Pull request by schonfeld**
This fixes the following issues with `useKeyboard()`:

* Properly remove all listeners
* Attach show & hide listeners to the correct callbacks
* Exposes the keyboard animation's duration and easing properties
* Refactor with eslint

### CODE REVIEW

**Comment by rikur** [comment]
LGTM, could this be merged please?

**Comment by pvinis** [comment]
I made some of these changes in the #41  PR. Could you check if you are happy with them there, and if you are, then we can close this PR. What do you think?

**Comment by pvinis** [comment]
Hello. Is the duration and easing something you still want added? If yes, could you resubmit this PR or fix the conflicts? I see that most of the code is already on master now. Thank you :)

**Comment by LinusU** [comment]
Closing since it seems inactive, if this is still a problem we would welcome an updated PR ☺️

**Pull request closed without merging**
