### PR TITLE
fix crash in android when hide keyboard

### PR DESCRIPTION
**Pull request by Gamal-Shaban**
# Summary
this fixes issue crash in android when hiding keyboard by checking `e` variable not null 

## Test Plan
  * show keyboard and hide will crash in android in old code
  * in new code fix crash in anroid

### What's required for testing (prerequisites)?
android keyboard

### What are the steps to reproduce (after prerequisites)?
when use (useKeyboard) hook in android and show keyboard and hide it will crash
because of variable `e` in function handleKeyboardDidHide was null in android 
I fix it checking for variable `e` is true   

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅   |
| Web     |    ✅    |

## Checklist

- [ * ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I've created a snack to demonstrate the changes: LINK HERE

### CODE REVIEW

**Comment by Gamal-Shaban** [comment]
@alloy

**Comment by pvinis** [comment]
Yep, that change makes sense. Thank you for that fix! :)

PS: No need to ping everyone in the world after 20 hours 😅 Give us at least a working day to process things, especially on a non-critical issue. Still, thank you for your contribution! :D

**Comment by Gamal-Shaban** [comment]
@pvinis  sorry

**Comment by pvinis** [comment]
:rocket: PR was released in `v2.4.8` :rocket:

**Comment by vonovak** [comment]
@Gamal-Shaban @pvinis shouldn't the `else` branch be covered as well? This way when the keyboard hides, consumers relying on `coordinates` will receive stale value

**Comment by pvinis** [comment]
Yep, that makes sense. We went from one bug to another. @Gamal-Shaban would you mind making a new PR to fix that too?

We should add some tests 😅 .

**Comment by Gamal-Shaban** [comment]
you are welcome @pvinis 
done
PR (add value to Coordinates when hide )

**Pull request merged**
