### PR TITLE
feat: add useRefresh hook

### PR DESCRIPTION
**Pull request by kanelloc**
# Summary
* Added `useRefresh` hook.
* It can be used with `<Flatlist/>`, `<SectionList/>`, `<VirtualizedList/>` and `<ScrollView/>`

### What's required for testing (prerequisites)?
```
yarn
yarn test
```

### What are the steps to reproduce (after prerequisites)?
Something like what is shown in the readme.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅    |
| Android |    ✅     |
| Web     |    ❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [x] I updated the typed files (TS and Flow)
- [ ] I've created a snack to demonstrate the changes: LINK HERE

### CODE REVIEW

**Comment by kanelloc** [comment]
Hey @LinusU 👋 !!
What do you think about this `useRefresh` hook?

**Comment by pvinis** [comment]
nice! I can take a look later today, if that's alright 👍

**Review by pvinis — APPROVED** [review]

**Comment by pvinis** [comment]
try it, and let me know if its alright!

**Comment by kanelloc** [comment]
> try it, and let me know if its alright!

Tested it and works as expected 🎉

**Pull request merged**
